export const initBookActions = {
    SELECT : 'SELECT',
    GET: 'GET',
    UPDATE_OR_ADD: 'UPDATE_OR_ADD',
    DELETE: 'DELETE',
    SEARCH: 'SEARCH',
    INIT_BOOKS: 'INIT_BOOKS',
    INIT_PARAMS: 'INIT_PARAMS',
    SET_NEW_SEARCH_PAGE: 'SET_NEW_SEARCH_PAGE',
    SET_PARAMS_QUERY: 'SET_PARAMS_QUERY',
    SET_PARAMS_ALL: 'SET_PARAMS_ALL'
}

export const initToggle = {
    MODIFY_TOGGLE: 'MODIFY_TOGGLE',
    MODAL_TOGGLE: 'MODAL_TOGGLE',
}